[package]
name = "fluvio-jolt"
version = "0.1.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
edition = "2021"
publish = false

[lib]
crate-type = ['cdylib', 'rlib']

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
