name: Publish Hub Dev

permissions: read-all

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch, tag or SHA to checkout"
        required: true
        type: string
        default: "main"

jobs:
  publish:
    uses: infinyon/fluvio/.github/workflows/smartmodule-publish.yml@master
    with:
      package-name: jolt
      branch: ${{ github.event.inputs.branch }}
      cloud-url: ${{ vars.DEV_CLOUD_URL }}
      fail-fast: false
    secrets: inherit
